export interface Product { id: string; name: string; sku: string; category: string; unit: string; totalStock: number; available: number; reserved: number; blocked: number; minStock: number; targetStock: number; reorderPoint: number; leadTimeDays: number; supplierId?: string; supplierName?: string; price?: number; status: string; lastMovementAt?: string; consumptionPerDay?: number; }
export interface Location { id: string; name: string; type: string; responsiblePerson?: string; itemCount: number; stockValue: number; criticalItems: number; lastMovementAt?: string; status: string; }
export interface Vehicle { id: string; name: string; licensePlate: string; responsiblePerson?: string; locationId?: string; locationName?: string; completeness: number; missingItems: number; criticalItems: number; lastCheckAt?: string; status: string; }
export interface Project { id: string; name: string; customer?: string; startDate: string; endDate?: string; status: string; projectManager?: string; materialStatus: string; missingItems: number; reservedPositions: number; openOrders: number; }
export interface PurchaseSuggestion { id: string; productId: string; productName: string; sku: string; locationId: string; locationName: string; currentStock: number; available: number; reserved: number; consumptionPerDay: number; daysOfSupply: number; leadTimeDays: number; targetStock: number; suggestedQty: number; supplierName: string; reason: string; severity: string; unit: string; }
export interface OrderPosition { id: string; productId: string; productName: string; sku: string; qty: number; unit: string; price: number; total: number; receivedQty: number; status: string; }
export interface PurchaseOrder { id: string; orderNumber: string; supplierId?: string; supplierName?: string; status: string; orderDate?: string; expectedDeliveryDate?: string; positions: OrderPosition[]; totalValue: number; projectId?: string; projectName?: string; }
export interface Alert { id: string; title: string; type: string; severity: string; productId?: string; productName?: string; locationId?: string; locationName?: string; recommendedAction: string; actionHref?: string; status: string; createdAt: string; vehicleId?: string; vehicleName?: string; projectId?: string; projectName?: string; responsible?: string; }
export interface Movement { id: string; productId: string; productName: string; type: string; quantity: number; fromLocationId?: string; fromLocationName?: string; toLocationId: string; toLocationName: string; referenceType?: string; referenceId?: string; createdAt: string; }
export interface DashboardKpi { label: string; value: number; status?: string; href: string; }
export interface DashboardRisk { id: string; title: string; severity: string; cause: string; action: string; actionHref: string; }
export interface KitItem { productId: string; productName: string; sku: string; targetQty: number; actualQty: number; unit: string; status: string; }
export interface Kit { id: string; name: string; type: string; vehicleId?: string; vehicleName?: string; responsiblePerson?: string; completeness: number; missingItems: number; lastCheckAt?: string; status: string; items: KitItem[]; }
export interface Equipment { id: string; name: string; serialNumber: string; locationId?: string; locationName?: string; responsiblePerson?: string; testStatus: string; nextTestDate?: string; lastTestDate?: string; isLocked: boolean; category?: string; }
